# Generated by Django 4.2 on 2025-03-27 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='Numéro de police')),
                ('type', models.CharField(choices=[('auto', 'Automobile'), ('home', 'Habitation'), ('health', 'Santé'), ('life', 'Vie'), ('business', 'Entreprise')], max_length=20, verbose_name='Type')),
                ('start_date', models.DateField(verbose_name="Date d'effet")),
                ('end_date', models.DateField(verbose_name="Date d'expiration")),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prime')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurances', to='clients.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_insurances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assurance',
                'verbose_name_plural': 'Assurances',
                'ordering': ['-created_at'],
            },
        ),
    ]
